name: 🔄 Sync and Deploy

on:
  push:
    branches:
      - depl

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Source Repo
        uses: actions/checkout@v4
        with:
          ref: depl
          fetch-depth: 0

      - name: 🔄 Push to Target Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'jikey8911'
          destination-repository-name: 'JeiKeiStattion_DokerDep'
          user-email: 'juanguzmanescandonfp@gmail.com'
          target-branch: main

      - name: 🚀 Update Oracle Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 147.224.220.58
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          connect_timeout: 30s
          script: |
            if [ ! -d "/home/ubuntu/JeiKeiStattion_DokerDep" ]; then
              git clone https://github.com/jikey8911/JeiKeiStattion_DokerDep.git /home/ubuntu/JeiKeiStattion_DokerDep
            fi
            
            cd /home/ubuntu/JeiKeiStattion_DokerDep
            git fetch origin main
            git reset --hard origin/main
            
            echo "🔄 Desplegando con docker-compose.prod.yml..."
            sudo docker compose -f docker-compose.prod.yml down
            sudo docker compose -f docker-compose.prod.yml up -d --build
            sudo docker image prune -f